p1 = input('请输入第1个数')
p2 = input('请输入第2个数')
p3 = input('请输入第3个数')
p4 = input('请输入第4个数')
p5 = input('请输入第5个数')
mList = [p1,p2,p3,p4,p5]
print('当前list为 %s' %mList)
print('第3个数为 : %s'%mList[2])
print('最后一个数为 : %s'%mList[-1])
p6 = input('请添加一个数')
mList.append(p6)
print('当前最新的list为 : %s' %mList)
p7 = input('请添加一个数')
index1 = input('选择插入位置,大于等于0,小于等于%s'%len(mList))
mList.insert(int(index1),p7)
print('当前最新list为 : %s'%mList)
index2 = input("选择删除一个数的位置 大于等于0,小于等于 %s" %len(mList))
mList.pop(int(index2))
print('当前最新list为 : %s'%mList)